### ISSUE TITLE
Performance issues in Java port

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#144]
Most of the Java port is done, but performance is currently horrible. This is issue is for tracking commits related to performance optimizations.

**Comment by samreid** [comment]
Before spending a lot of work on micro-optimizations, it would be great to (a) quantify the performance on an iPad platform and (b) try rendering the animating objects using WebGL (or simply commenting them out) to see if that buys enough CPU to make the sim run smoothly.  I have encountered situations where the benefit from using WebGL vastly outweighed any micro optimization, reducing garbage collection, etc. and we need to see if that is the case here.

**Comment by bereaphysics** [comment]
The benefit of WebGL would be minimal. The source of the problems lies in the model. The way the simulations goes about finding the new positions is too simplistic. 
For reasons that are not very clear to me, the positions for the next time step are requested with a very large precision. The way the model goes about finding the positions with a high precision is to used a not very precise algorithm but splicing the time step further but 400. Of course you do less error that way but you have 400 times the work. and vector allocation galore, and no time left for garbage collections since your system is busy doing all these updates, etc. 

For molecular dynamics, chemists have developed algorithms with a higher precision than the simple verlet-velocity approach.  Verlet is precise to order tau^2. but there are symplectic algorithm with a tau^4 and tau^6 order. They are (initially) more complicated but then you don't have to subdivide your time interval further avoiding all these vector allocations. 

@aaronsamuel137 I can give you reference about it or I could work on it. 

Ultimately, it may not get us to 60fps, but right now 96% of CPU time is spent in the updating loop of the model , so it is the most  pressing bottleneck.

**Comment by bereaphysics** [comment]
This paper explains it. 
http://www.sciencedirect.com/science/article/pii/0375960190900923

The authors work out the 4th, 6th and 8th order algorithms.  I can help you parse the paper since it is written with Poisson Bracket notation, which you are unlikely to be familiar with.

**Comment by bereaphysics** [comment]
This paper
http://arxiv.org/pdf/cond-mat/0110585v1.pdf
uses a notation that is a bit more conventional. Equation 22 shows the algorithm.

**Comment by aaronsamuel137** [comment]
Some performance metrics with the two algorithms:

|                 | Current algorithm | new algorithm |
--------------|--------------------------|--------------------|
Chrome Mac laptop (everything on) | 47fps               | 60 fps            |
iPad mini (everything on) | 15 fps | 15-20 fps |
iPad mini (everything off) | 30 fps | 30 fps

Visibly, it is difficult to notice too much difference between the two (to my eye). Despite the low frame rate on iPad, the sim doesn't appear too choppy except during a mode switch and right after pressing play, which seems unrelated to the model update algorithm.

**Comment by bereaphysics** [comment]
While doing some testing for correctness, i mistakenly committed this

https://github.com/phetsims/gravity-and-orbits/commit/135f9285ea59704d3dd63b4ea4ea073efeb42e40

```
         var bodyStates = this.bodies.map( function( body ) {return body.toBodyState();} );
         var newState = new ModelState( bodyStates ).getNextState(
           dt,
-          1 / SMOOTHING_STEPS, // 1000 looks great, 50 starts to look awkward for sun+earth+moon, but 100 seems okay.
+          40 / SMOOTHING_STEPS, // 1000 looks great, 50 starts to look awkward for sun+earth+moon, but 100 seems okay.
           // Update: 100 is poor for sun/earth/moon system in "to scale" because the orbit is gradually expanding.
           // Tests suggest 400 is a good performance/precision tradeoff
           this.gravityEnabledProperty
````

this should be reverted. 1 / SMOOTHING_STEPS does as well as 40 / SMOOTHING_STEPS

**Comment by samreid** [comment]
Here's a snapshot from the paper of the algorithm:

![image](https://cloud.githubusercontent.com/assets/679486/9972771/c6defc8e-5e25-11e5-978d-9b49d40f0646.png)

**Comment by aaronsamuel137** [comment]
Removing radial gradients for sun and unknown body nodes and replacing with images increased performance by quite a bit.

On my iPad mini, on the exponential algorithm branch, I was getting between 20-35 fps for just the earth orbiting around the sun. Without the radial gradients, I am getting between 25-55 fps.

In both cases the frame rate bounces around quite a lot for no apparent reason. There is no user interaction, just watching the earth around the sun.

**Comment by ariel-phet** [comment]
@jessegreenberg should probably review this issue to see what was done in the past to improve performance

**Comment by jessegreenberg** [comment]
Reviewed, this was also helpful for issue #220.  Closing this issue since the port performs well now, other than #162 (deferred, opened in scenery).
