### ISSUE TITLE
Should teacherMode and whiteBackgroundProperty be stripped from the Java port

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/gravity-and-orbits#146]
teacherMode and whiteBackgroundProperty are both features in the Java code that were not present in the MLL port. Should I strip these totally out of the new direct port?

Not sure who I should ask. @samreid, I think you were involved in the original Java. @ariel-phet, any thoughts on this?

**Comment by samreid** [comment]
Would also be good to ask @jonathanolson since I recall he created some view options for molecule shapes. (if I recall correctly)

**Comment by ariel-phet** [comment]
Hmm, we probably want to keep these...we often refer to these more modernly as "projector mode" - when you have a classroom that is bright, it can sometimes be difficult to project sims with a black background (since black is not a "projected" color, but just the absence of color), so as a general policy we have had a projector mode for black background sims. @bereaphysics also did a nice job with this in Charges and Fields.

**Comment by jonathanolson** [comment]
See GlobalOptionsNode in charges-and-fields or molecule-shapes for an example. You can also view either of those sims for an example of how to change color schemes (which could use some standardization and code-sharing if you're up for it).

**Comment by aaronsamuel137** [comment]
I've added a GlobalOptionsNode in a way that is similar to molecule-shapes. However, I didn't create a GravityAndOrbitsColors file modeled after MoleculeShapesColors. Is this the recommended approach? With a direct port, it is easier to just leave things as they are, and switch the colors with the "whiteBackgroundProperty". Any thoughts on this @jonathanolson? Perhaps we could also bring it up in dev meeting.

Also, is there going to be any redesign of "whiteBackground" color profile? That may determine how we approach this. @ariel-phet, how does the white background in GAO look to you? (on master)

**Comment by jonathanolson** [comment]
I had to change almost every color in my sim, so it was by far the easiest to work with color properties (and have the switch change the color properties). Additionally, the boolean was insufficient since there are (currently) three color profiles for Molecule Shapes (and Basics).

I'd probably personally opt towards that same method in the future, since it's quite extensible easily (need to add another color profile? simple. need to change colors on something that didn't change colors before? no code changes needed since everything already was hooked up). Additionally, it allows easy tweaking of colors by the sim designer / team, so they can just report ideal colors after tweaks to me (no color back-and-forth discussions needed, which had taken up a lot of time in the past).

**Comment by aaronsamuel137** [comment]
I've replaced whiteBackgroundProperty with the new color profile pattern. Closing
