### ISSUE TITLE
Moon is returned relative to earth rather than initial position

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-and-orbits#241]
For the moon + earth system, the 'return object' behavior seems strange.  For most bodies, the return object button places the body back at the initial position.  For the moon, the moon is placed in the initial position relative to the earth.  This creates situations like this:

![recording 1](https://cloud.githubusercontent.com/assets/6396244/19956158/a3d96de2-a14e-11e6-89e1-a85ce4bbbc4a.gif)

It makes it seem like the 'return' button is broken. @arouinfar is this correct?

**Comment by jessegreenberg** [comment]
Hmm, seems like this was considered fixed in https://github.com/phetsims/gravity-and-orbits/issues/156?  But I can't find more information about this.

**Comment by jessegreenberg** [comment]
Yes, this is not a bug.
```js
        // Restore the moon near the earth and with the same relative velocity vector
          var relativePosition = this.positionProperty.initialValue.minus( earth.positionProperty.initialValue );
          this.positionProperty.set( earth.positionProperty.get().plus( relativePosition ) );
          var relativeVelocity = this.velocityProperty.initialValue.minus( earth.velocityProperty.initialValue );
          this.velocityProperty.set( earth.velocityProperty.get().plus( relativeVelocity ) );
```

@arouinfar do you know why it should behave like this?

**Comment by arouinfar** [comment]
I find this behavior a bit odd @jessegreenberg. In general, it seems like return object takes the object back to its initial state. Instead, I think it would make more sense for <i>all</i> objects to return to their saved state. Basically, return object would behave like the rewind button.

Consider this situation. First we save a new state, by pausing and dragging the sun elsewhere. 
<img width="1084" alt="screen shot 2016-11-07 at 12 27 46 pm" src="https://cloud.githubusercontent.com/assets/8419308/20072592/3d6ee10e-a4e6-11e6-88ae-5aa1e97ffae1.png">

After hitting play, the earth will eventually make its way off screen. 
<img width="1087" alt="screen shot 2016-11-07 at 12 28 15 pm" src="https://cloud.githubusercontent.com/assets/8419308/20072596/3f871d1c-a4e6-11e6-85dc-4c64979e37f3.png">

The return object button pauses the sim, and returns the earth to its initial position (leaving the moon in the sun's orbit).
<img width="1086" alt="screen shot 2016-11-07 at 12 29 33 pm" src="https://cloud.githubusercontent.com/assets/8419308/20072601/41465f32-a4e6-11e6-96e8-0af574b191ae.png">

This doesn't seem useful at all. Instead, I think the return object button should restore the saved state (like the rewind button). If no state has been saved, all objects would return to their initial position. 

Even though it's redundant, I think we should keep the return object button because it serves as a visual cue to the users. They may not intuitively click on rewind or reset after an object is lost off-screen. However, let's rename it "Return Objects".

**Comment by arouinfar** [comment]
To summarize:
* Return object button will behave exactly like the rewind button.
* Rename it "Return Objects" since multiple objects may be moved.

**Comment by jessegreenberg** [comment]
Sounds good @arouinfar.  Should the 'Return Objects' button pause the sim like before, or should the sim continue playing once objects are returned?

**Comment by jessegreenberg** [comment]
Commit above should fix this, and if we need to we can easily pause the sim once the 'Return Objects' button is pressed.  At the moment, it does not pause the sim because the rewind doesn't either.  But the 'Return Objects' button used to pause the sim, so perhaps this is where it should differ from the 'Rewind' button.

**Comment by arouinfar** [comment]
> But the 'Return Objects' button used to pause the sim, so perhaps this is where it should differ from the 'Rewind' button.

I agree @jessegreenberg. I wasn't thinking about this difference earlier. Can you please update the Return Objects button so that it pauses the sim?

**Comment by jessegreenberg** [comment]
The system is now paused when the objects are returned.  Thanks @arouinfar, I think your recommendations in https://github.com/phetsims/gravity-and-orbits/issues/241#issuecomment-258942338 have improved the consistency of this feature.

Closing.
