### ISSUE TITLE
branch: uniform-dt

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#269]
Identified by `print-branches.sh`. @jessegreenberg please describe.

**Comment by jessegreenberg** [comment]
This branch is for https://github.com/phetsims/gravity-and-orbits/issues/253.

That issue reports that different playback speeds can create different orbits from the same initial conditions. The fix had a negative impact on performance so the issue was deferred. Anyone picking up #253 should start from work in this branch.

**Comment by samreid** [comment]
@jessegreenberg and I reviewed this branch today and concluded that the fixes in #253 are in good shape, and nothing needs to be preserved from this branch.  We deleted the branch, closing.
