### ISSUE TITLE
User suggestion: variable slider for orbital radius

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-and-orbits#275]
> Can you add a variable slider for orbital radius, or an additional tab that lets students explore Kepler's 3rd law for multiple satellites, in the Gravity and Orbits sim? The best we can do at the moment is slingshot the orbiting object into a new orbit, but the timing is tricky.

**Comment by samreid** [comment]
@arouinfar or @ariel-phet would like like to work on this for the upcoming publication?

**Comment by arouinfar** [comment]
This is an interesting suggestion. I think it might be nice to someday add a slider for semi-major axis (since that's what's Kepler's 3rd Law) but I think it will take some design work in terms of space constraints and scaffolding/flow.

I don't know the constraints on the GAO work in terms of priorities and timelines, but this seems like a bigger change than #268 (but smaller-scale than #270). I would be fine with deferring this feature.

**Comment by ariel-phet** [comment]
I am not sure I understand the request. I feel like this request is actually sort of covered...you just have to adjust the orbital radius to begin with by moving the planet, before pressing play. Once it is moving things are trickier, agreed. I however do not think we should be making a change like a orbital radius slider at this time.

**Comment by arouinfar** [comment]
While this issue is still somewhat fresh, a few final thoughts...

>  I feel like this request is actually sort of covered...you just have to adjust the orbital radius to begin with by moving the planet, before pressing play.

Yes, but only somewhat. You can change the initial distance, but it will be hard to extract the T^2 ~ a^3 relationship. There's some tricky geometry going on -- the user is changing the distance at perihelion, not the semi-major axis directly. 

In this screenshot, the useful distance is represented by the cyan line. It can be estimated by counting gridlines (magenta line divided by 2), and I got reasonable agreement with Kepler's 3rd Law. 
![image](https://user-images.githubusercontent.com/8419308/67246113-cc92a380-f41a-11e9-9e88-cc7296e3f82f.png)

After going through this exercise, I honestly think this learning goal is much better supported by My Solar System. I'm tempted to close this issue, but I'll leave it open just in case GAO gets revisited again before My Solar System is redesigned.

**Comment by samreid** [comment]
> I'll leave it open just in case GAO gets revisited again before My Solar System is redesigned.

@arouinfar do you recommend we incorporate this with the Gravity and Orbits PhET-iO work we are doing now?

**Comment by arouinfar** [comment]
@samreid I think this is best addressed in My Solar System, so I'll go ahead and close.

I will add some information about grid spacing/Kepler's 3rd Law to the Teacher Tips when I update them in #325.
