### ISSUE TITLE
Should fast motion be 7x slow motion, or 8x slow motion?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#285]
During #253 I noticed that fast speed is 7x slow speed.  The current values are:

Slow: 1 step
Normal: 4 steps
Fast: 7 steps.

I just wanted to double check that the 7x factor is desired.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
@samreid that does seem a bit odd to me. My guess is that the speed settings are a holdover from Java, and weren't ever explicitly discussed in the HTML5 design. The Earth/Moon and Earth/Satellite are pretty fast in the published version, so perhaps that's why we went with an odd step-size. I don't think we need to make fast any faster.

Even if we made fast forward 8x slow motion, the spacing will still be a bit funky. Slow would be 1/4x normal speed, and fast would be 2x normal speed. Let's leave things as-is @samreid.
