### ISSUE TITLE
Revise model values for the space station

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#307]
From https://github.com/phetsims/gravity-and-orbits/issues/295#issuecomment-591597100, @arouinfar said:

I checked the `massProperty`, `diameterProperty`, `speedProperty`, `forceMagnitudeProperty`, and the pair-wise `distanceProperty` on the To Scale screen for all bodies. For the most part things are looking good, but I did notice some discrepancies for the satellite (defaults should match the International Space Station).

| Property | satellite default | [ISS](https://www.nasa.gov/feature/facts-and-figures) | 
| --- | --- | --- | 
| mass | 369914 kg | 419725 kg | 
| diameter | 218000 m | 73m x 109m |

`satellite.diamterProperty` is way off the mark, but I'm not sure if it's actually used for anything in the model. A more reasonable value would probably be the average of the length/width which would be 91 m. Likewise, `satellite.massProperty` is off by a fair amount, so we should probably update that as well.

**Comment by samreid** [comment]
In the above commit, I set the space station mass and radius as prescribed.  I noticed there is a fudge factor of 1000x in the diameter (even in the "To Scale" screen) to make the space station big enough to see.  I removed the 1000x fudge factor for the commit, but I'm wondering if should leave it in the sim, just not as a part of the `diameterProperty`.  But if someone uses the measuring tape, they will measure the wrong size for the space station.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
> I set the space station mass and radius as prescribed.

Thanks! The mass looks good.

Looking more carefully at https://github.com/phetsims/gravity-and-orbits/commit/ba6fceb5570caf79e3b95ed52f4df17f9160fb01, I see that the value in the model for `SPACE_STATION_RADIUS` was 109 m (which is the ISS's longest dimension). However, the value I was seeing in studio for `modelScreen.model.planetSatelliteScene.satellite.diameterProperty` was significantly different (218000 m). 

Similarly, now that the `SPACE_STATION_RADIUS` is based on the average dimension (91/2), the value of `modelScreen.model.planetSatelliteScene.satellite.diameterProperty` is still way off (728 m).

> I noticed there is a fudge factor of 1000x in the diameter (even in the "To Scale" screen) to make the space station big enough to see. I removed the 1000x fudge factor for the commit, but I'm wondering if should leave it in the sim, just not as a part of the diameterProperty. 

I think we definitely want the fudge factor for the Model screen, otherwise the space station isn't visible, but I don't think it's something we need to expose to the client or include in the `diameterProperty`.

> But if someone uses the measuring tape, they will measure the wrong size for the space station. 

This shouldn't be a problem of the fudge factor only exists on the Model screen. The measuring tape is only available on the To Scale screen.

**Comment by samreid** [comment]
I noticed there was another factor of 8x in the "model" radius for the space station here:

https://github.com/phetsims/gravity-and-orbits/blob/b5c87702503d6c8ba1a1e1685810d0e1b9e8bd6d/js/model/ModelSceneFactory.js#L110-L116

It was my understanding from https://github.com/phetsims/gravity-and-orbits/issues/302#issuecomment-586820602 that the "Model" screen values for radii would be purposefully inaccurate.  How do you recommend to proceed?

**Comment by arouinfar** [comment]
Discussed with @kathy-phet.

On the Model screen, the `diameterProperty` of the Earth and Satellite do not need to be accurate. The satellite is inflated so it is visible, and to maintain clearance between the bodies, the earth is reduced a bit, which is how the published sim behaved.
![image](https://user-images.githubusercontent.com/8419308/76808346-1ce51600-67ad-11ea-9dfd-53a20cd20d39.png)

These values should be accurate on the Model screen (currently correct in master):
`modelScreen.model.planetSatelliteScene.planetSatellitePair.distanceProperty` 
`modelScreen.model.planetSatelliteScene.planet.massProperty`
`modelScreen.model.planetSatelliteScene.satellite.massProperty`

**Comment by samreid** [comment]
I found that scaling the satellite radius by a factor of around 20000x is pretty close to the published version.  @arouinfar can you please review?  You can compare this by launching phettest and visually comparing the Earth/Satellite scene to the published version.  Anything else for this issue?

**Comment by kathy-phet** [comment]
Looks good to us! Closing.
