### ISSUE TITLE
Measuring Tape gets stuck under Fast/Normal/Slow buttons

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/gravity-and-orbits#361]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Chrome and Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/519
When on the To Scale sim, you can move the measuring tape under the Fast/Normal/Slow buttons and it can get stuck under them. Can be fixed by resetting the sim or zooming in/out. Can reproduce on published sim as well.

**Steps to reproduce**
1. Click To Scale section. 
2. Click the check mark on the measuring tape. 
3. Move the measuring tape under the Fast/Normal/Slow buttons (under Normal is best area)

**Visuals**
![gravmeasuretape](https://user-images.githubusercontent.com/72031637/95618518-6e474200-0a2a-11eb-9d7e-0c99be66a45e.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet/gravity-and-orbits_all_phet.html
Version: 1.2.0-dev.16 2020-09-15 16:33:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
Nice find @brooklynlash. We generally try to layer the MeasuringTapeNode on top of everything else. For example:
![image](https://user-images.githubusercontent.com/8419308/96056353-91675c80-0e43-11eb-99cb-6125a5e6eb68.png)
![image](https://user-images.githubusercontent.com/8419308/96056369-9cba8800-0e43-11eb-9353-8d6b4121fae2.png)

 
@samreid let's change the z-order of the MeasuringTapeNode so that it's on top of the TimeControlNode.

**Comment by samreid** [comment]
In this simulation, there are 2 competing nodes:

1. The scene, which contains the planets and measuring tape and grid
2. The screen, which contains the control panels, reset all button & time controls 

These are currently not interleaved.

Putting the Scene first (as in master now) means the measuring tape goes behind all screen things.
Putting the Screen first would work well for the measuring tape, but puts the grid in front of the control panels.

![image](https://user-images.githubusercontent.com/679486/96274576-e57e5800-0f8d-11eb-93fa-a6a01129c39c.png)

**Comment by samreid** [comment]
@arouinfar do you want the planets and other bodies to also go in front of the "Fast/Normal/Slow" buttons etc?  Is the grid the only thing that should be in the back?  Will we need to interleave the nodes or split into more than 2 layers?

**Comment by arouinfar** [comment]
Oh, that is more complicated than I realized @samreid. I think this issue is relatively minor, and I don't know that it warrants interleaving the nodes or a more complicated layering approach.

It's not ideal that the MeasuringTapeNode can get (temporarily) trapped behind the radio buttons, but I don't think it's a terribly realistic use case. 

I'm fine with closing this as wont-fix @samreid. If you agree, please close. If you'd rather adjust the layering, let me know and I'll make a recommendation.

**Comment by samreid** [comment]
I don't believe we should try to fix this before the upcoming dev "rc-lite" release.  I don't feel strongly one way or the other about whether this is fixed for the next main release.  Based on the preceding remark, I'm inclined to close, but anyone please reopen if you disagree.
