### ISSUE TITLE
Text properties and client guide instruction for text that isn't there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#370]
For https://github.com/phetsims/QA/issues/576
The client guide asks for:
>When a body is small, the indicatorNode appears. To change the label, edit the associated textProperty.

The Model screen section has three elements. However, only the first one actually has a label in the sim. The other two do not and changing their text does not seem to do anything from what I can see.

<img width="734" alt="nothingthere" src="https://user-images.githubusercontent.com/41024075/100164402-00899500-2e75-11eb-9599-cd503181929f.png">

**Comment by samreid** [comment]
`gravityAndOrbits.modelScreen.view.playAreaNode.starPlanetMoonSceneView.planetNode.indicatorNode.visibleProperty` is not featured, so in order to see it, you have to select "All".  Also, if you zoom out far enough, the planet label automatically becomes visible:

![image](https://user-images.githubusercontent.com/679486/100379659-75beac80-2fd2-11eb-9309-fcc87d1bf42f.png)

@arouinfar how do you recommend to proceed?

**Comment by arouinfar** [comment]
>`gravityAndOrbits.modelScreen.view.playAreaNode.starPlanetMoonSceneView.planetNode.indicatorNode.labelNode.textProperty`
`gravityAndOrbits.modelScreen.view.playAreaNode.starPlanetSceneView.planetNode.indicatorNode.labelNode.textProperty`

These labels are only visible when the user zooms out far enough. Technically, all bodies have an associated `labelNode.textProperty` but I only included those that a user could potentially see.

While the associated phetioIDs for most client requests will be featured, it's not always the case. Here, we don't necessarily want people changing the names of the bodies, so it's not featured.

I don't think there's anything we need to do here, so closing.
