### ISSUE TITLE
Noticeable lag in Phet-io playback wrapper

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/gravity-and-orbits#376]
For https://github.com/phetsims/QA/issues/595, seen on Win10 Firefox and Edge only. 
There is about 11+ seconds of lag when playing back the Gravity and Orbits phet-io recording, it stops at the 1 second mark, pauses, and then quickly skips to the 12 second mark or further. I have not seen this on other sims and it was replicated on master. 

Note: my gif creator is somewhat laggy as well so it speeds up to the "real time" a bit quicker when replicating. 

Visuals: 
![GOrecording](https://user-images.githubusercontent.com/72031637/109549897-d22adf80-7a8b-11eb-8bb4-2f97f725e769.gif)

**Comment by zepumph** [comment]
>and then quickly skips to the 12 second mark or further

One potential solution for this part would be in the playback wrapper. Since there is just a single definition of "time progressed" in the playback wrapper, when something occurs very slowly, it pushes back every event afterwards. So events that could play normally are actually played much quicker. Perhaps we could work this out in the playback wrapper to reset the clock when we detect that an event took longer in the playback wrapper than it did in the recording.

I'll will caveat this whole issue by saying that the playback wrapper isn't really supposed to be a production-level application. At least not in practice. We have perhaps had two researchers back in 2017 use it. Otherwise it is a tool we use to confirm that recording is working as expected. So minor details like this speed-up/lag don't bother me at all (except to entice me with the fun algorithms that could be employed to fix them, like above).

**Comment by zepumph** [comment]
I also want to add that I encountered the exact same lag in BAA over in https://github.com/phetsims/special-ops/issues/190. To be clear, this is just generally laggy because of qualities of our playback algorithm (like async event passing). Though it is correlated to the complexity of the sim's playback, I'm unsure how much there is to be done within each sim.

**Comment by KatieWoe** [comment]
This is in https://github.com/phetsims/QA/issues/624

**Comment by samreid** [comment]
Based on https://github.com/phetsims/gravity-and-orbits/issues/376#issuecomment-790176971, I don't think this issues would block RC.2.

**Comment by samreid** [comment]
Using `?screens=1` cuts the lag in about half, perhaps it is the long list of messages emitted on startup that are causing the problem?

**Comment by zepumph** [comment]
We no longer support this wrapper, so I'm going to close this issue as a wontfix, see https://github.com/phetsims/phet-io/issues/1854
