### ISSUE TITLE
Rewind button behavior on G&O intentional?

### ISSUE THREAD

**Issue by DevonQui** [phetsims/gravity-and-orbits#378]
**Test device**
MacBook Pro

**Operating System**
11.2.1

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/595

I was messing around with the rewind button on the simulation and was just wondering why it doesn't allow the user to step-back. Instead it just functions as a scene reset button but I think it would be useful to have a step-back button seeing that there are moments where an instructor/student might want to step-back to a certain moment instead of having to do a scene reset and then resuming the sim again.

**Visuals**
Here's a link to the visuals
https://drive.google.com/file/d/1M9Unq7tbcV_saNibMUEdiRm4pfcmhfOP/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.4.0-rc.1 2021-01-28 19:09:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by emily-phet** [comment]
Unassigning myself - I was a designer on this sim when it was first developed, but likely @arouinfar is the lead designer now.

**Comment by samreid** [comment]
The desired behavior of the rewind button is to return to the initial conditions where the user last dragged an object.  For instance:

1. Launch the sim and go to screen 1.
2. Drag the Earth to the opposite side of the sun
3. Press play
4. Press rewind, and observe that the Earth is where it was dropped, rather than the initial setup for that scene

We designed the rewind button so that the user could set up an experiment and run it again and again.  

I don't think adding a "step backwards" or "run time backwards" will be added in this version, but perhaps we may want something like that in a future version.

@arouinfar any other thoughts for this issue?  Feel free to close.

**Comment by arouinfar** [comment]
Thanks for your question @DevonQui. 

@samreid thanks for the explanation. I don't think we a step back button would serve any of the primary learning goals of this simulation, and it could potentially be complicated when dealing with destroyed objects. There were a lot of oddities with saved states and stepping back that came up in Collision Lab (where it's critical to see moments before/after collision), and I really don't want to repeat that here.
