### ISSUE TITLE
"screen" prefix is not used for keys related to screen names.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#412]
Noticed while working on https://github.com/phetsims/joist/issues/764.

This sim does not use the convention of using the "screen" prefix for the keys that correspond to screen names.

In gravity-and-orbits-strings_en.json, the keys for the string titles should be `"screen.model"` and `"screen.toScale"`.

**Comment by samreid** [comment]
Good catch, I am unfamiliar with how key names can be changed and weighing that against the importance of this convention.  @jbphet can you please advise?

**Comment by jbphet** [comment]
There is a document that describes how to change a string key for a published sim, please see https://github.com/phetsims/rosetta/blob/master/doc/how-to-change-a-string-key.md.

It looks like a lot of translations have been submitted for this sim, so I'm not sure it would be worth it to change the key.  If we don't have any tools that rely on this convention, it may not be worth the effect.  Ultimately it will be up to you @samreid.

**Comment by samreid** [comment]
Due to the significant amount of work to change keys, and the lack of operational requirements for enforcing this convention, I recommend we leave this as an unchanged legacy case.  I also skimmed through other sims alphabetically to see if I could quickly find other cases where they do not follow the convention.  I saw:

* Area Builder explore screen key is just "explore"
* Area Builder explore game key is just "game"
* Arithmetic has "divide", "factor" and "multiply"
* Balancing act and its 3 screens
* Build an Atom

I stopped looking after the "B" sims. @pixelzoom sound OK to close?

**Comment by pixelzoom** [comment]
Not my call. That's probably a question for PhET-iO designers, since the fact that the screen names are not where they should be is exposed in the Studio.

**Comment by zepumph** [comment]
We discussed this during PhET-iO meeting today. We all agree that this convention (starting the key with `screen.`) would be nice to have, and we want it in the future.

We are not going to change the GAO string keys before publication.

We see ~160 usages of screen keys using this, about ~280 new screens on the project, so our coverage is quite poor. @samreid  astutely noted that the issue here is mainly that https://github.com/phetsims/rosetta/blob/master/doc/how-to-change-a-string-key.md#changing-a-string-key-for-a-simulation is much too challenging, and it would be nice to have a simple utility to rename string keys for us. Then we could have the right string keys. @kathy-phet noted that we will make an epic for that.

Marking for dev meeting as a simple PSA about continuing to follow this convention. 

We also maybe want to add a bogus example name to the Screen in simula-rasa.

**Comment by zepumph** [comment]
Discussed at dev meeting today. PSA complete.
* Not going to change old names
* Update Simula rasa to demonstrate this example.
* Not making it easy to change a string key (at this time), but at some point in the future!
