### ISSUE TITLE
Restart button disabled when it shouldn't be

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gravity-and-orbits#415]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
safari

**Problem description**
While testing https://github.com/phetsims/qa/issues/744, I noticed this Gravity and Orbits issue (doesn't look like a typescript issue):

In the Studio wrapper, if you press play, pause the sim, and then launch the sim, the Restart button will be grayed out (disabled). 
This is also seen in the State wrapper. 

**Steps to reproduce**
In Studio:
1. On either screen, press Play and then Pause--all of the Time Control buttons will be blue
2. Press 'Launch Sim' button. The Restart button will be grayed out.

In State:
1. On either screen, press Play and then Pause--all of the Time Control buttons will be blue in the upstream sim. In the downstream sim, the Restart button will be grayed out. 

**Visuals**
![restartbutton](https://user-images.githubusercontent.com/87318828/146066528-523308d5-fc8f-47f0-bb42-493ac7e77229.gif)

<img width="528" alt="Screen Shot 2021-12-14 at 2 01 54 PM" src="https://user-images.githubusercontent.com/87318828/146065060-b50ff6cd-3c58-4b69-b0af-d866134232ed.png">

**Comment by samreid** [comment]
I'll evaluate this when we return to gravity-and-orbits, unassigning for now.

**Comment by samreid** [comment]
The scene reset behavior under customized phet-io state was described here: https://github.com/phetsims/gravity-and-orbits/issues/343 and approved as working well.

For this issue, the state is now transmitting well:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/679486/188986816-86ce4f7d-2c00-414f-bec7-981bf11171bf.png">

But perhaps it doesn't matter because of the behavior prescribed in https://github.com/phetsims/gravity-and-orbits/issues/343 anyways.  I recommend closing this issue, but @Nancy-Salpepi or @arouinfar please feel free to reopen at your discretion.
