### ISSUE TITLE
Object in launched sim may change orientation if time is stepped back

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#457]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/838.
When a sim is launched, the step back time control is available. However, it "steps back" to the location it was at when launched. If the sim is paused, this should mean nothing happens. However, the orientation of the object is changed.
**Steps to reproduce**
1. Go to the Model screen and the Planet and Satellite scene
2. Play the sim briefly
3. Pause the sim
4. Launch the sim
5. In the launched sim, hit the step back button and observe the satellite

**Visuals**
![changeorientation](https://user-images.githubusercontent.com/41024075/193155086-bdaa52fb-4276-449f-a8f7-c9541b518ac2.gif)

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

@samreid this looks like a problem with the `rotationProperty` of the object. It's easiest to observe with the satellite, but it's a general problem.

Here's an example following @KatieWoe's steps to reproduce, but with the PlanetMoonScene.

`rotationProperty` = -1.92... radians in Studio and the initial configuration of the Standard PhET-iO Wrapper:
![image](https://user-images.githubusercontent.com/8419308/193900235-2580ebc4-74bd-42f8-bad4-c92206713832.png)

`rotationProperty` resets to zero when pressing the Restart button in the Standard PhET-iO Wrapper:
![image](https://user-images.githubusercontent.com/8419308/193900462-a0091668-b442-4c9b-bfcc-2b00b7e30aa3.png)

It seems like the `rotationProperty` is excluded from the state saved by the Restart button, which may explain why the button is enabled by default in the Standard PhET-iO Wrapper. I would expect it to be disabled because the initial state in the wrapper should be identical to the state restored with the Restart button.

**Comment by arouinfar** [comment]
> It seems like the `rotationProperty` is excluded from the state saved by the Restart button, which may explain why the button is enabled by default in the Standard PhET-iO Wrapper. 

I compared to the 1.5 version, and the Restart button is disabled in the Standard PhET-iO Wrapper, as I would expect. However, if you play or step forward to enable the restart button, and then press restart, it will restore a state with the `rotationProperty` = 0.

**Comment by samreid** [comment]
Fixed and ready for cherry-pick

**Comment by KatieWoe** [comment]
This seems fixed in RC.3
